[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[dev]
  functions = "netlify/functions"
  port = 8888

# Configuração de funções Edge
[[edge_functions]]
path = "/gemini-api"
function = "gemini-api"

[[edge_functions]]
path = "/youtube-api"
function = "youtube-api"

# Redirecionamento geral da PWA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Exceção para o arquivo de teste
[[redirects]]
from = "/test-no-fallback.html"
to = "/test-no-fallback.html"
status = 200
force = true

